# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rpackage_wrappers", use_symbols = TRUE, package_name = "rpackage")

#' @docType package
#' @usage NULL
#' @useDynLib rpackage, .registration = TRUE
NULL

#' @export
hello_world <- function() .Call(wrap__hello_world)

#' This function adds two numbers.
#' @export
add <- function(a, b) .Call(wrap__add, a, b)

#' This function subtracts two numbers.
#' @export
subtract <- function(a, b) .Call(wrap__subtract, a, b)

#' This function multiplies two numbers.
#' @export
multiply <- function(a, b) .Call(wrap__multiply, a, b)

#' This function divides two numbers.
#' @export
divide <- function(a, b) .Call(wrap__divide, a, b)

